### ISSUE TITLE
Cannot set response_type

### ISSUE THREAD

**Issue by fanglansheng** [zalando/oauth2-client-js#12]
Hi, the authorization endpoint I am working with need to set response_type as "id_token token".
However I found the request I sent only had "token". Then I find out that in your OAuthImplicitRequest constructor, the response_type is overwrote to be "config.response_type = 'token';". It doesn't set nonce either. Would you consider to change it?

**Comment by lasomethingsomething** [comment]
Hi @prayerslayer, wondering what you think of @fanglansheng's idea ...

**Comment by prayerslayer** [comment]
Uh, that's quite old, I apologize. So if I understand correctly, you want to set the `response_type` in the request to another value than `token`. That's something I don't favor a lot because it's how the RFC tells us to do it.

However making this possible in a clean way is something @schlessera wanted to work on as mentioned in #14.

**Comment by fragsalat** [comment]
Seems like the need is gone
